apiVersion: v1
kind: Service
metadata:
  name: coturn-service
spec:
  selector:
    app: coturn
  ports:
    - name: turn-udp
      protocol: UDP
      port: 3478
      targetPort: 3478
    - name: turn-tcp
      protocol: TCP
      port: 3478
      targetPort: 3478
  type: LoadBalancer
